# -*- coding: utf-8 -*-
"""Primeiros codigos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywIaSZRjt8GZ95APEnpL5s_2NWbCFs1n

# ***Calculadora Simples***

***Essa calculadora irá mostrar a adcao, subtração, divisao e multiplicação dos mumeros que forem digitados dos dois numero digitados.***
"""

numeroUm = input("Digite seu primeiro numero") # Aguarda o usuario digitar
print ("seu numero digitado foi = ", numeroUm)

numeroDois = input("Digite o segundo numero") # Aguarda o usuario digitar
print ("seu numero digitado foi = ", numeroDois)

print("O resultado subtraido,adcionado,dividido e mutiplicado é")
valor_um = float(numeroUm)
valor_dois = float(numeroDois)
desconto = valor_um - valor_dois
acrescimo = valor_um + valor_dois
dividido = valor_um / valor_dois
mutiplica = valor_um * valor_dois
print(desconto)
print(acrescimo)
print(dividido)
print(mutiplica)

"""# ***Calculadora usando while***"""

while True:
    print("\nCalculadora usando while")
    print("Escolha a operação:")
    print("1 Soma")
    print("2 Subtração")
    print("3 Multiplicação")
    print("4 Divisão")
    print("5 Sair")

    digito = input("Digite o número da operação desejada: ")

    if digito == "5":
        print("Calculadora desligada")
        break

    if digito not in ["1", "2", "3", "4"]:
        print("Opção inválida. Tente novamente.")
        continue

    try:
        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))
    except ValueError:
        print("Entrada inválida. Use apenas números.")
        continue

    if digito == "1":
        resultado = num1 + num2
        print(f"Resultado: {num1} + {num2} = {resultado}")
    elif digito == "2":
        resultado = num1 - num2
        print(f"Resultado: {num1} - {num2} = {resultado}")
    elif digito == "3":
        resultado = num1 * num2
        print(f"Resultado: {num1} * {num2} = {resultado}")
    elif digito == "4":
        print(f"Resultado: {num1} / {num2} = {resultado}")